# Generated by Django 2.2.1 on 2021-02-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default=None, verbose_name='질문')),
                ('answer', models.TextField(default=None, verbose_name='답변')),
            ],
        ),
    ]
