# Generated by Django 2.2.1 on 2021-02-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeaddbyuser',
            name='region',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
