# Generated by Django 2.2.1 on 2021-02-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210209_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='areaselection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_region', models.CharField(blank=True, choices=[('kr', '전체'), ('kr', '강남구'), ('kr', '강동구'), ('kr', '강북구'), ('kr', '강서구'), ('kr', '관악구'), ('kr', '광진구'), ('kr', '구로구'), ('kr', '금천구'), ('kr', '노원구'), ('kr', '도봉구'), ('kr', '동대문구'), ('kr', '동작구'), ('kr', '마포구'), ('kr', '서대문구'), ('kr', '서초구'), ('kr', '성동구'), ('kr', '성북구'), ('kr', '송파구'), ('kr', '양천구'), ('kr', '영등포구'), ('kr', '용산구'), ('kr', '은평구'), ('kr', '종로구'), ('kr', '중구'), ('kr', '중랑구')], max_length=5)),
            ],
        ),
    ]
