# Generated by Django 2.2.1 on 2021-02-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_areaselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeaddbyuser',
            name='xmap',
            field=models.DecimalField(decimal_places=13, max_digits=20),
        ),
        migrations.AlterField(
            model_name='placeaddbyuser',
            name='ymap',
            field=models.DecimalField(decimal_places=13, max_digits=20),
        ),
    ]
