# Generated by Django 2.2.1 on 2021-02-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20210215_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeaddbyuser',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
