# Generated by Django 2.2.1 on 2021-02-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20210217_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeaddbyuser',
            options={'verbose_name': 'placeAddByUser', 'verbose_name_plural': 'placesAddByUser'},
        ),
    ]
