# Generated by Django 2.2.1 on 2021-02-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20210219_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeaddbyuser',
            options={'verbose_name': 'placeAddByUser', 'verbose_name_plural': 'placeAddByUsers'},
        ),
    ]
