# Generated by Django 2.2.1 on 2021-02-04 19:50

from django.db import migrations, models
import piroproject.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_likes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=piroproject.utils.uuid_upload_to),
        ),
    ]
