# Generated by Django 2.2.1 on 2021-02-04 20:15

from django.db import migrations, models
import piroproject.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210204_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=piroproject.utils.uuid_upload_to),
        ),
    ]
