# Generated by Django 2.2.1 on 2021-02-04 21:03

from django.db import migrations, models
import piroproject.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=piroproject.utils.uuid_upload_to),
        ),
    ]
