# Generated by Django 2.2.1 on 2021-02-04 21:26

from django.db import migrations, models
import piroproject.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=piroproject.utils.uuid_upload_to),
        ),
    ]
