# Generated by Django 2.2.1 on 2021-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=None, verbose_name='댓글내용'),
        ),
    ]
