# Generated by Django 2.2.1 on 2021-02-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='secret',
            field=models.BooleanField(default=False, verbose_name='secret'),
        ),
    ]
